version: "3.8"

services:
  app:
    init: true
    image: demo_rtsp/app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    restart: always